name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  docker_push:
    runs-on: self-hosted

    steps:
    -
        name: Pull Docker Image
        run: sudo docker pull rupzz/my-first-project
    -
        name: Delete Old Docker Container
        run: sudo docker rm -f rupzz/my-first-project|| true
    -
        name: Run docker container
        run: sudo docker run -d -p 80:80 -m 100m --name my-first-project rupzz/my-first-project:latest
