name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login Docker Hub
      env: 
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_PASSWOR: "${{ secrets.DOCKER_PASSWORD }}"
      run: docker login -u  $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run:  docker build -t my-first-project 

    - name: Push to Docker Hub
      run: docker push roopika-19/my-first-project:latest
